### PR TITLE
Fixing regex identify keyword in terms of another languages.

### PR DESCRIPTION
**Pull request by juniorb2ss**
We are having trouble using terms or words in other languages.

For example: If we implement some code comment that contains the word `METODO PAGO` in Spanish, the bot identifies and creates an issue.

### CODE REVIEW

**Comment by JasonEtco** [comment]
Hey folks - thanks for opening this 🙏 I see the issue here, but its unfortunately a little complicated. Because TODO operates on strings, not ASTs, it relies on vague matching; so this PR would prevent comments like this from trigger an issue:

```
@todo ...
```

Because there's no space after the `@`, and its not the start of the line. `.*` will match it, albeit very aggressively. There should be a test for this behavior that would have failed.

For this case, it might be worth tightening up your configured keyword to `// TODO`:

```yaml
# .github/config.yml
todo:
  keyword: "// TODO"
```

Let me know if that helps!

**Comment by juniorb2ss** [comment]
Hello @JasonEtco! Thanks for reply.

Yeah... this expression does not prevent `@todo` or something like 😞 About tests, I agree. 

> There should be a test for this behavior that would have failed.

Maybe need implement a test to prevent use of `@todo` too.

It may be somewhat unworkable to change the configured tag. We use this plugin in several private repositories, and our team has the custom of using `TODO: ...`

Maybe a `strictMode` flag would be interesting instead of changing the expression?

`stringMode: false`

```
METODO PAGO // will catch
```

`stringMode: true`

```
METODO PAGO // don't catch
```

I don't know... just try to give some ideia in specific use.

> Hey folks - thanks for opening this 🙏 I see the issue here, but its unfortunately a little complicated. Because TODO operates on strings, not ASTs, it relies on vague matching; so this PR would prevent comments like this from trigger an issue:
> 
> ```
> @todo ...
> ```
> 
> Because there's no space after the `@`, and its not the start of the line. `.*` will match it, albeit very aggressively. There should be a test for this behavior that would have failed.
> 
> For this case, it might be worth tightening up your configured keyword to `// TODO`:
> 
> ```yaml
> # .github/config.yml
> todo:
>   keyword: "// TODO"
> ```
> 
> Let me know if that helps!

**Comment by juniorb2ss** [comment]
Hello @JasonEtco! Thanks for reply.

This expression really does not provide for `@ everything`. 😞 

Only way is change the configured tag to `// TODO`.

About tests... I think is good idea implement a test to cover use of `@todo`... to avoid future PR with broken changes.

> Hey folks - thanks for opening this 🙏 I see the issue here, but its unfortunately a little complicated. Because TODO operates on strings, not ASTs, it relies on vague matching; so this PR would prevent comments like this from trigger an issue:
> 
> ```
> @todo ...
> ```
> 
> Because there's no space after the `@`, and its not the start of the line. `.*` will match it, albeit very aggressively. There should be a test for this behavior that would have failed.
> 
> For this case, it might be worth tightening up your configured keyword to `// TODO`:
> 
> ```yaml
> # .github/config.yml
> todo:
>   keyword: "// TODO"
> ```
> 
> Let me know if that helps!

**Comment by juniorb2ss** [comment]
@JasonEtco 

Thinking better... should not `@todo` be set to default instead of using an aggressive regex like `. *` To predict usage?

Any tag different of `TODO` and `@todo` need configured. So, why implement regex `.*` to prevent this occurrences?

We're discussing a bot issue. I do not think it's a better way to "change the settings". But we try to find a regex that predicts these cases too.

> Hey folks - thanks for opening this 🙏 I see the issue here, but its unfortunately a little complicated. Because TODO operates on strings, not ASTs, it relies on vague matching; so this PR would prevent comments like this from trigger an issue:
> 
> ```
> @todo ...
> ```
> 
> Because there's no space after the `@`, and its not the start of the line. `.*` will match it, albeit very aggressively. There should be a test for this behavior that would have failed.
> 
> For this case, it might be worth tightening up your configured keyword to `// TODO`:
> 
> ```yaml
> # .github/config.yml
> todo:
>   keyword: "// TODO"
> ```
> 
> Let me know if that helps!

**Pull request closed without merging**
