### PR TITLE
Added emoji to label

### PR DESCRIPTION
**Pull request by AshanthaLahiru**
Referring to the issue https://github.com/JasonEtco/todo/issues/113

### CODE REVIEW

**Comment by rsarky** [comment]
Looks good to me. :+1: 
We will need to change some tests tho.

**Comment by JasonEtco** [comment]
@AshanthaLahiru thanks for doing this! The reason the tests are failing is that the project uses Jest's [Snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html), so when the output of a function or method changes those snapshots have to be updated. You can do that by running the `npm run test:update` script 😄

**Comment by AshanthaLahiru** [comment]
Oh cool, that's my bad :smile: 

@JasonEtco , I tried as you said. Even the generate-label pass the test. Few others are failing. I'm little bit confused here. Could you help?

testingerror1
testerror2

**Comment by JasonEtco** [comment]
@AshanthaLahiru that's odd since the tests are passing on TravisCI (aside from the snapshot issue). Can you remove changes to the snapshot files, then run `npm test` and paste a screenshot of the output here?

**Comment by AshanthaLahiru** [comment]
@JasonEtco , Sure.

npm_test_result_1
npm_test_result_2
npm_test_result_3

**Comment by JasonEtco** [comment]
I've pulled down your branch and ran the tests on my own machine (also a PC) and the only tests that are failing are related to the snapshots. Since it seems like an issue with your setup, I'm going to update those snapshots and merge this PR 😀

**Comment by AshanthaLahiru** [comment]
@JasonEtco , Yes, it seems my setup issue. I'll look into that. Thank you for the support. :smiley:

**Pull request merged**
